[project]
name = "agentic-workflows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.59.9",
    "python-dotenv>=1.0.1",
    "schedule>=1.2.2",
]
